
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURET = "USER_REGISTRATION_FAILURET";

export const FETCH_BUDGET_lIST_REQUEST = "FETCH_BUDGET_lIST_REQUEST";
export const FETCH_BUDGET_lIST_SUCCESS = "FETCH_BUDGET_lIST_SUCCESS";
export const FETCH_BUDGET_lIST_FAILURE = "FETCH_BUDGET_lIST_FAILURE";
export const SAVE_BUDGET_REQUEST = "SAVE_BUDGET_REQUEST";
export const SAVE_BUDGET_SUCCESS = "SAVE_BUDGET_SUCCESS";
export const SAVE_BUDGET_FAILURE = "SAVE_BUDGET_FAILURE";
export const DELETE_BUDGET_REQUEST = "DELETE_BUDGET_REQUEST";
export const DELETE_BUDGET_SUCCESS = "DELETE_BUDGET_SUCCESS";
export const DELETE_BUDGET_FAILURE = "DELETE_BUDGET_FAILURE";

export const FETCH_EXPENSE_lIST_REQUEST = "FETCH_EXPENSE_lIST_REQUEST";
export const FETCH_EXPENSE_lIST_SUCCESS = "FETCH_EXPENSE_lIST_SUCCESS";
export const FETCH_EXPENSE_lIST_FAILURE = "FETCH_EXPENSE_lIST_FAILURE";
export const SAVE_EXPENSE_REQUEST = "SAVE_EXPENSE_REQUEST";
export const SAVE_EXPENSE_SUCCESS = "SAVE_EXPENSE_SUCCESS";
export const SAVE_EXPENSE_FAILURE = "SAVE_EXPENSE_FAILURE";
export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";